### ISSUE TITLE
task definition, ECR設定の自動化

### ISSUE THREAD

**Issue by selmertsx** [speee/webapp-revieee#2]
基本的な Railsアプリならば、review appsのアカウントを 
GitHubのcollaboratorに追加する & webhook を設定するだけで
運用が可能となっている

ECR + Task Definitionの自動初期設定
- Rails側でのhandling (初期設定が無ければ作るなど)
- Dockerfileの自動生成
- 生成したdocker imageをECRにpushする
- 対応した TaskDefinitionを生成する

**Comment by pataiji** [comment]
#3 #20 #21 に分割
