### ISSUE TITLE
IAMとECRを作成し、ユーザーがECRにプロダクトのイメージをpushできるようにする

### ISSUE THREAD

**Issue by pataiji** [speee/webapp-revieee#20]
## やりたいこと
ユーザーが作ったDocker ImageをECRにpushできるようにしたい。

### ECR
- speee-dev のaws account にて、ECRにpushするために必要な権限 (IAM)
- ECRにpushするための repository_name 

## 実現しなければならないこと
- ECRに Image をpushするための仕組みを作る
- それを作る

https://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#create_repository-instance_method

**Comment by selmertsx** [comment]
## やりたいこと
Dockerfileを書かずとも、Docker Imageを作って、ECRにpushできるようにしたい。

## Docker Imageの作成に必要な情報
- settings.local.yml 
- database.yml 
- github にアクセスするための秘密鍵

## ECRにpushするために必要な情報
- speee-dev のaws account にて、ECRにpushするために必要な権限 (IAM)
- ECRにpushするための repository_name 


https://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#create_repository-instance_method

**Comment by selmertsx** [comment]
## 作りたいIAM
- 指定された ECR にのみ pushできる
- (create はだれがいつやろう)

## TODO
- [ ] 指定された ECR のみに push できる IAMを考える
- [ ] ↑を作って配布する方法を考える

**Comment by selmertsx** [comment]
## ユースケース
1. プロダクトに所属しているエンジニアが、revieee使いたいリクエストを基盤部に飛ばす
2. 基盤部がECR・IAMを作成し、アクセスするための情報をプロダクトのエンジニアに渡す
3. プロダクトのエンジニアは、渡されたECR URI・IAMを使って、自分のサービス用のECRに docker imageをpushする

## TODO
- IAM作成
- ECR作成
- ECRに任意のIAMでアクセスできるようにする

参考資料
rdoc: http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#create_policy-instance_method

http://docs.aws.amazon.com/ja_jp/AmazonECR/latest/userguide/RepositoryPolicyExamples.html

**Comment by selmertsx** [comment]
## 作成するECRリポジトリポリシー


```json
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "AllowAll",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::aws_account_id:user/new_user"
      },
      "Action": [
        "ecr:*"
      ]
    }
  ]
}
```

**Comment by selmertsx** [comment]
## 作成するIAM Group
名前 SpeeeDeveloperで行く

```
resp = client.create_group({
  group_name: "SpeeeDeveloper", 
})
```

http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#create_group-instance_method

**Comment by selmertsx** [comment]
## 作成する IAM User

```ruby
resp = client.create_user({
  user_name: "Bob", 
})
```

```
resp = client.add_user_to_group({
  group_name: "SpeeeDeveloper", 
  user_name: "Bob", 
})
```

userを作成:
http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#create_user-instance_method

userをgroupに追加: http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#add_user_to_group-instance_method

**Comment by selmertsx** [comment]
## ECRの作成

```ruby
# This example creates a repository called nginx-web-app inside the project-a namespace in the default registry for an account.

resp = client.create_repository({
  repository_name: "project-a/nginx-web-app", 
})

# resp.to_h outputs the following:
{
  repository: {
    registry_id: "012345678901", 
    repository_arn: "arn:aws:ecr:us-west-2:012345678901:repository/project-a/nginx-web-app", 
    repository_name: "project-a/nginx-web-app", 
  }, 
}
```

http://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#create_repository-instance_method

## ECRの権限設定

```ruby
resp = client.set_repository_policy({
  registry_id: "RegistryId",
  repository_name: "RepositoryName", # required
  policy_text: "RepositoryPolicyText", # required
  force: false,
})
```

http://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#set_repository_policy-instance_method

- ちょっとイメージしてたのと違うっぽい。
- getしてデータ眺めたりして方法を模索する

イメージしてたやつ
http://docs.aws.amazon.com/ja_jp/AmazonECR/latest/userguide/RepositoryPolicyExamples.html

**Comment by selmertsx** [comment]
rake taskとして作成できたので、このissueはclose
