### ISSUE TITLE
test時のrails_configの仕様を考える

### ISSUE THREAD

**Issue by pataiji** [speee/webapp-revieee#26]
https://github.com/speee/webapp-revieee/pull/24#discussion_r103615611

**Comment by selmertsx** [comment]
https://github.com/railsconfig/config#accessing-the-settings-object

> Settings defined in files that are lower in the list override settings higher.

```
config/settings.yml
config/settings/#{environment}.yml
config/environments/#{environment}.yml

config/settings.local.yml
config/settings/#{environment}.local.yml
config/environments/#{environment}.local.yml
```

**Comment by selmertsx** [comment]
Its correct behavior for config gems.
so we have two choices.

- Create config/settings.test.yml and remove from gitignore.
- Leave this settings as it is.

**Comment by selmertsx** [comment]
https://github.com/railsconfig/config/issues/135
