### ISSUE TITLE
リポジトリとTask Definitionの関連付けをDBで管理する

### ISSUE THREAD

**Issue by selmertsx** [speee/webapp-revieee#3]

**Comment by pataiji** [comment]
Model
- TaskDefinition
  - name
  - repository_name

今あるTaskDefinition Classと統合する

**Comment by pataiji** [comment]
@selmertsx で、どうですかね？

**Comment by selmertsx** [comment]
@pataiji 
正しくtask_definitionのお仕事っぽい！良いと思います :+1:
