### ISSUE TITLE
task削除時にDBからレコードが削除されていない様子

### ISSUE THREAD

**Issue by pataiji** [speee/webapp-revieee#31]
![db](https://cloud.githubusercontent.com/assets/1869952/23732451/88aa83d2-04b6-11e7-9c33-e4a428456464.png)
![web](https://cloud.githubusercontent.com/assets/1869952/23732455/8b4ad934-04b6-11e7-9bbd-ae5560f23260.png)

**Comment by selmertsx** [comment]
https://github.com/speee/webapp-revieee/issues/43

このバグからの派生。

```ruby
class PullRequest::Actions::Close < PullRequest::Actions
  def handle
    target.cache_clear_urls.each do |url|
      Net::HTTP.get url
    end

    return unless target.delete
    add_comment('ReviewAppsを削除しました')
  end
end

```

cache clear時にエラーが起きていたため、task削除に到達できていなかった。
