### ISSUE TITLE
複数のポート公開対応

### ISSUE THREAD

**Issue by selmertsx** [speee/webapp-revieee#4]

**Comment by pataiji** [comment]
**endpoiints**

| name | type | nullable | index |
| ----- | ----- | -------- | ----- |
| id | integer | false | primary |
| identifier | varchar(255) | false | unique indexed |
| ip | varchar(15) | false | |
| port | smallint(6) unsigned | false | |
| task_id | integer(11) | false | indexed |

**tasks**

| name | type | nullable | index |
| ----- | ----- | -------- | ----- |
| id | integer | false | primary |
| arn | varchar(255) | false |

@selmertsx DBこんな感じでどうでしょうか？
`endpoints`という名前でいいのか非常に不安

**Comment by pataiji** [comment]
@selmertsx 
アクセスするURLですが、`pr_number+ip+portのMD5`.reviewapps.example.com にしたいんですがどう思います？
(むしろuuidですらいいかも)

理由は
- domainからアクセス先のcontainerが判別できればいいだけ
- 実装がシンプルにできる

からです

↓ `Task Definition Name`-pr-`Pull Request Number`-ps-`Container Name`.reviewapps.example.com にするとtaskモデルにreview_app_targetを渡す必要が出てくる
https://github.com/speee/webapp-revieee/blob/4-multiple-port-publication/app/models/task.rb#L18

**Comment by selmertsx** [comment]
https://github.com/speee/webapp-revieee/issues/4#issuecomment-276585007

identifier が少し悩ましいですね。IDとの違いが何なのか少し考えることになりそうです。
通常使っている IDを、autoincrementやめて、自前で降っても良いかもですね。

**Comment by pataiji** [comment]
そうなんですよね。
primary key変えるのめんどくさくはあるものの、変えちゃっていいならこうしたいですかね。

**endpoints**

| name | type | nullable | index |
| ----- | ----- | -------- | ----- |
| identifier | varchar(255) | false | primary |
| ip | varchar(15) | false | |
| port | smallint(6) unsigned | false | |
| task_id | integer(11) | false | indexed |

**tasks**

| name | type | nullable | index |
| ----- | ----- | -------- | ----- |
| pr_number| int | false | primary |
| arn | varchar(255) | false | |

**Comment by pataiji** [comment]
- `identifier`は`id`を略してないだけなので微妙
- `identifier`ではなく`id`をvarcharとして定義したいけどRails、関連gemがintegerとして扱わないかが気になる

結果

**endpoints**

| name | type | nullable | index |
| ----- | ----- | -------- | ----- |
| id | integer | false | primary |
| subdomain | varchar(255) | false | unique |
| ip | varchar(15) | false | |
| port | smallint(6) unsigned | false | |
| task_id | integer(11) | false | indexed |

**Comment by selmertsx** [comment]
https://github.com/speee/webapp-revieee/issues/4#issuecomment-276600064

> pr_number+ip+portのMD5.reviewapps.example.com

こちら、シンプルで良いと思います！
閉じられた環境で使う予定ですし、最初は直 port でも良いくらいかなと

**Comment by pataiji** [comment]
(repository+pr_number+ip+port)のMD5.reviewapps.example.com
すみません、でした:pray:

**Comment by selmertsx** [comment]
把握しました！
MD5だと長さが固定されるということで、そちらのメリットの方が大きそうなので、MD5にしますか！

**Comment by kou** [comment]
`subdomain`は既存の情報（`repository`と`pr_number`と`ip`と`port`）から計算できるようなので、データベースには入れなくていいんじゃないかと思いました！

もし、`subdomain`が推測可能であってもよいなら、`endpoints`の`id`をサブドメインとして使っちゃってもいいのかもなぁと思いました。例：`endpoint1.reviewapps.example.com`（サブドメインはアルファベットから始めなければいけないので`1`の前に`endpoint`をつけてみた。）

**Comment by kou** [comment]
（あ、`subdomain`をデータベースに入れておかないとクライアントからアクセスされたときに該当エンドポイントのポート番号とかを引くのが大変、というのは理解しているつもりです。なので、サブドメインをMD5とか元の情報を取得できないものにするならデータベースに入れるほうがよいと思います！）

**Comment by pataiji** [comment]
> もし、subdomainが推測可能であってもよいなら、endpointsのidをサブドメインとして使っちゃってもいいのかもなぁと思いました。例：endpoint1.reviewapps.example.com（サブドメインはアルファベットから始めなければいけないので1の前にendpointをつけてみた。）

なるほどです！
社内で使用するものだしレコード数が分かっても問題はないのでたしかに`id`でいいかも.....
どうでしょう？ > @selmertsx

**Comment by selmertsx** [comment]
> 社内で使用するものだしレコード数が分かっても問題はないのでたしかにidでいいかも.....

パフォーマンスから考えても、idが良さそう！！
